export const margin = { top: 30, right: 30, bottom: 30, left: 30 };
export const verticalSpacing = 25;
export const maxTextBoxWidth = 200;
export const fontSize = 14;
export const lineHeight = fontSize * 1.5;
export const textBoxPadding = 10;
export const defaultHeight = 300;
//export const viewWidth = 4500;
export const viewWidth = 3000;
